import type { Product } from "@/lib/types"

export const products: Product[] = [
  // Himalayan Grocery Store (id: 1)
  {
    id: "p1",
    shopId: "1",
    name: "Fresh Local Tomatoes",
    nameNepali: "स्थानीय गोलभेडा",
    description: "Farm-fresh tomatoes sourced from local farmers in Kathmandu Valley. Perfect for curries and salads.",
    price: 80,
    images: ["https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=400&h=400&fit=crop"],
    category: "fresh-produce",
    inStock: true,
    stockCount: 50,
    unit: "kg",
    featured: true,
  },
  {
    id: "p2",
    shopId: "1",
    name: "Basmati Rice Premium",
    nameNepali: "बासमती चामल",
    description: "Long-grain aromatic basmati rice, perfect for biryani and pulao.",
    price: 220,
    compareAtPrice: 250,
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop"],
    category: "grains",
    inStock: true,
    stockCount: 100,
    unit: "kg",
  },
  {
    id: "p3",
    shopId: "1",
    name: "Fresh Spinach Bunch",
    nameNepali: "पालुंगो",
    description: "Organic spinach from local farms. Rich in iron and vitamins.",
    price: 40,
    images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop"],
    category: "fresh-produce",
    inStock: true,
    stockCount: 30,
    unit: "bunch",
  },
  {
    id: "p4",
    shopId: "1",
    name: "Nepali Masala Mix",
    nameNepali: "नेपाली मसला",
    description: "Traditional blend of spices for authentic Nepali cooking.",
    price: 150,
    images: ["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop"],
    category: "spices",
    inStock: true,
    stockCount: 45,
    unit: "200g",
    featured: true,
  },
  {
    id: "p5",
    shopId: "1",
    name: "DDC Fresh Milk",
    nameNepali: "डीडीसी दूध",
    description: "Fresh pasteurized milk from DDC. 500ml pack.",
    price: 55,
    images: ["https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop"],
    category: "dairy",
    inStock: true,
    stockCount: 60,
    unit: "500ml",
  },

  // Nepal Fashion House (id: 2)
  {
    id: "p6",
    shopId: "2",
    name: "Daura Suruwal Set",
    nameNepali: "दौरा सुरुवाल सेट",
    description: "Traditional Nepali formal wear for men. Includes daura, suruwal, and topi.",
    price: 4500,
    compareAtPrice: 5000,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=400&fit=crop"],
    category: "traditional",
    inStock: true,
    stockCount: 15,
    variants: [
      { id: "v1", name: "Small", price: 4500, inStock: true },
      { id: "v2", name: "Medium", price: 4500, inStock: true },
      { id: "v3", name: "Large", price: 4500, inStock: true },
      { id: "v4", name: "XL", price: 4800, inStock: false },
    ],
    featured: true,
  },
  {
    id: "p7",
    shopId: "2",
    name: "Dhaka Topi",
    nameNepali: "ढाका टोपी",
    description: "Authentic Dhaka topi handwoven in Nepal. Symbol of Nepali culture.",
    price: 800,
    images: ["https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 40,
  },
  {
    id: "p8",
    shopId: "2",
    name: "Pashmina Shawl",
    nameNepali: "पश्मिना शल",
    description: "Luxurious 100% cashmere pashmina shawl. Handwoven in Nepal.",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 25,
    featured: true,
  },

  // Tech Hub Electronics (id: 3)
  {
    id: "p9",
    shopId: "3",
    name: "Samsung Galaxy A54",
    nameNepali: "स्याम्सङ ग्यालेक्सी A54",
    description: "5G smartphone with 128GB storage, 6GB RAM. Excellent camera and battery life.",
    price: 52000,
    compareAtPrice: 55000,
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop"],
    category: "smartphones",
    inStock: true,
    stockCount: 12,
    featured: true,
  },
  {
    id: "p10",
    shopId: "3",
    name: "Wireless Earbuds Pro",
    nameNepali: "वायरलेस इयरबड्स प्रो",
    description: "Active noise cancellation, 24-hour battery life with case.",
    price: 4500,
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 35,
  },
  {
    id: "p11",
    shopId: "3",
    name: "USB-C Fast Charger 65W",
    nameNepali: "USB-C फास्ट चार्जर",
    description: "Universal fast charger compatible with laptops and phones.",
    price: 2200,
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 50,
  },

  // Patan Handicrafts (id: 4)
  {
    id: "p12",
    shopId: "4",
    name: "Tibetan Singing Bowl",
    nameNepali: "तिब्बती गायन कटोरा",
    description: "Hand-hammered brass singing bowl for meditation. Includes wooden mallet.",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=400&h=400&fit=crop"],
    category: "singing-bowls",
    inStock: true,
    stockCount: 20,
    featured: true,
  },
  {
    id: "p13",
    shopId: "4",
    name: "Thangka Painting - Buddha",
    nameNepali: "थाङ्का चित्र - बुद्ध",
    description: "Hand-painted thangka of Buddha. Natural mineral colors on cotton canvas.",
    price: 15000,
    images: ["https://images.unsplash.com/photo-1609710228159-0fa9bd7c0827?w=400&h=400&fit=crop"],
    category: "thangka",
    inStock: true,
    stockCount: 8,
  },
  {
    id: "p14",
    shopId: "4",
    name: "Wooden Prayer Wheel",
    nameNepali: "काठको माने",
    description: "Traditional Buddhist prayer wheel with mantras. Handcrafted wood and brass.",
    price: 1800,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop"],
    category: "wood-carving",
    inStock: true,
    stockCount: 15,
  },

  // Glow Beauty Store (id: 5)
  {
    id: "p15",
    shopId: "5",
    name: "Himalayan Face Serum",
    nameNepali: "हिमालयन फेस सीरम",
    description: "Natural anti-aging serum with Himalayan herbs. Brightens and hydrates skin.",
    price: 1200,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop"],
    category: "skincare",
    inStock: true,
    stockCount: 30,
    featured: true,
  },
  {
    id: "p16",
    shopId: "5",
    name: "Organic Lip Balm Set",
    nameNepali: "अर्गानिक लिप बाम सेट",
    description: "Set of 3 natural lip balms with honey, rose, and mint flavors.",
    price: 450,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop"],
    category: "skincare",
    inStock: true,
    stockCount: 45,
  },

  // Book Worm Corner (id: 6)
  {
    id: "p17",
    shopId: "6",
    name: "Palpasa Cafe - Narayan Wagle",
    nameNepali: "पल्पसा क्याफे",
    description: "Bestselling Nepali novel set during the Maoist insurgency. A love story.",
    price: 450,
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop"],
    category: "nepali-literature",
    inStock: true,
    stockCount: 25,
    featured: true,
  },
  {
    id: "p18",
    shopId: "6",
    name: "Into Thin Air - Jon Krakauer",
    nameNepali: "इनटु थिन एयर",
    description: "Account of the 1996 Everest disaster. A must-read for mountaineering enthusiasts.",
    price: 850,
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop"],
    category: "non-fiction",
    inStock: true,
    stockCount: 18,
  },

  // Bhaktapur Pottery (id: 7)
  {
    id: "p19",
    shopId: "7",
    name: "Traditional Clay Pot",
    nameNepali: "माटोको भाँडो",
    description: "Handmade clay cooking pot. Perfect for traditional dal preparation.",
    price: 600,
    images: ["https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&h=400&fit=crop"],
    category: "pottery",
    inStock: true,
    stockCount: 30,
    featured: true,
  },
  {
    id: "p20",
    shopId: "7",
    name: "Decorative Vase Set",
    nameNepali: "सजावटी फूलदानी सेट",
    description: "Set of 3 hand-painted ceramic vases. Traditional Bhaktapur design.",
    price: 2500,
    images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400&h=400&fit=crop"],
    category: "decorative",
    inStock: true,
    stockCount: 12,
  },

  // Everest Sports (id: 8)
  {
    id: "p21",
    shopId: "8",
    name: "Trekking Backpack 60L",
    nameNepali: "ट्रेकिङ ब्याकप्याक",
    description: "Durable trekking backpack with rain cover. Multiple compartments.",
    price: 5500,
    compareAtPrice: 6000,
    images: ["https://images.unsplash.com/photo-1622260614153-03223fb72052?w=400&h=400&fit=crop"],
    category: "trekking",
    inStock: true,
    stockCount: 20,
    featured: true,
  },
  {
    id: "p22",
    shopId: "8",
    name: "Sleeping Bag -10°C",
    nameNepali: "स्लीपिङ ब्याग",
    description: "Warm sleeping bag suitable for high-altitude treks.",
    price: 4200,
    images: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&h=400&fit=crop"],
    category: "camping",
    inStock: true,
    stockCount: 15,
  },

  // Newari Sweets (id: 9)
  {
    id: "p23",
    shopId: "9",
    name: "Yomari (6 pcs)",
    nameNepali: "योमरी",
    description: "Traditional Newari sweet dumplings filled with chaku and sesame.",
    price: 350,
    images: ["https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=400&fit=crop"],
    category: "sweets",
    inStock: true,
    stockCount: 40,
    featured: true,
  },
  {
    id: "p24",
    shopId: "9",
    name: "Chatamari",
    nameNepali: "चतामरी",
    description: "Newari rice crepe topped with egg and minced meat. Ready to eat.",
    price: 180,
    images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=400&fit=crop"],
    category: "traditional",
    inStock: true,
    stockCount: 25,
  },
  {
    id: "p25",
    shopId: "9",
    name: "Sel Roti (Pack of 10)",
    nameNepali: "सेल रोटी",
    description: "Traditional ring-shaped sweet bread. Perfect for festivals.",
    price: 200,
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop"],
    category: "traditional",
    inStock: true,
    stockCount: 50,
  },

  // Lakshmi Gold & Silver (id: 10)
  {
    id: "p26",
    shopId: "10",
    name: "Silver Filigree Earrings",
    nameNepali: "चाँदीको कर्णफूल",
    description: "Handcrafted silver filigree earrings. Traditional Nepali design.",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop"],
    category: "silver",
    inStock: true,
    stockCount: 20,
    featured: true,
  },
  {
    id: "p27",
    shopId: "10",
    name: "Gold Mangalsutra",
    nameNepali: "सुनको मंगलसूत्र",
    description: "22K gold mangalsutra with black beads. Traditional bridal jewelry.",
    price: 45000,
    images: ["https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop"],
    category: "gold",
    inStock: true,
    stockCount: 5,
  },

  // Organic Farm Fresh (id: 11)
  {
    id: "p28",
    shopId: "11",
    name: "Organic Vegetable Box",
    nameNepali: "अर्गानिक तरकारी बक्स",
    description: "Weekly box of seasonal organic vegetables. Feeds family of 4.",
    price: 1200,
    images: ["https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=400&fit=crop"],
    category: "organic",
    inStock: true,
    stockCount: 30,
    featured: true,
  },
  {
    id: "p29",
    shopId: "11",
    name: "Free Range Eggs (12 pcs)",
    nameNepali: "फ्रि रेन्ज अण्डा",
    description: "Farm-fresh eggs from free-range chickens.",
    price: 280,
    images: ["https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop"],
    category: "eggs",
    inStock: true,
    stockCount: 50,
  },

  // Trendy Threads (id: 12)
  {
    id: "p30",
    shopId: "12",
    name: "Designer Kurti",
    nameNepali: "डिजाइनर कुर्ती",
    description: "Modern printed kurti with embroidery. Comfortable cotton fabric.",
    price: 1800,
    compareAtPrice: 2200,
    images: ["https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&h=400&fit=crop"],
    category: "women",
    inStock: true,
    stockCount: 25,
    variants: [
      { id: "v5", name: "S", price: 1800, inStock: true },
      { id: "v6", name: "M", price: 1800, inStock: true },
      { id: "v7", name: "L", price: 1800, inStock: true },
      { id: "v8", name: "XL", price: 1800, inStock: false },
    ],
    featured: true,
  },
  {
    id: "p31",
    shopId: "12",
    name: "Men's Casual Shirt",
    nameNepali: "पुरुष क्यजुअल सर्ट",
    description: "Cotton casual shirt with modern fit. Available in multiple colors.",
    price: 1500,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop"],
    category: "men",
    inStock: true,
    stockCount: 30,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByShopId(shopId: string): Product[] {
  return products.filter((product) => product.shopId === shopId)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowerQuery) ||
      product.nameNepali?.includes(query) ||
      product.description.toLowerCase().includes(lowerQuery) ||
      product.category.toLowerCase().includes(lowerQuery)
  )
}

export function getProductsByCategory(shopId: string, category: string): Product[] {
  return products.filter(
    (product) => product.shopId === shopId && product.category === category
  )
}
