import type { Product } from "@/lib/types"

export const products: Product[] = [
  // Himalaya Asian Mart (id: 1) - groceries
  {
    id: "p1",
    shopId: "1",
    name: "Wai Wai Noodles (Pack of 5)",
    nameNepali: "वाइ वाइ चाउचाउ",
    description: "The iconic Nepali instant noodles. A taste of home that every Nepali in Japan craves. Pack of 5.",
    price: 450,
    images: ["https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400&h=400&fit=crop"],
    category: "snacks",
    inStock: true,
    stockCount: 120,
    unit: "5-pack",
    featured: true,
  },
  {
    id: "p2",
    shopId: "1",
    name: "Basmati Rice 5kg",
    nameNepali: "बासमती चामल ५ केजी",
    description: "Premium long-grain aromatic basmati rice. Perfect for biryani, pulao, and everyday dal bhat.",
    price: 2980,
    compareAtPrice: 3400,
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop"],
    category: "rice",
    inStock: true,
    stockCount: 80,
    unit: "5kg bag",
    featured: true,
  },
  {
    id: "p3",
    shopId: "1",
    name: "Masoor Dal (Red Lentils) 1kg",
    nameNepali: "मसुरको दाल १ केजी",
    description: "Premium quality red lentils for authentic Nepali dal. Cooks quickly and tastes just like home.",
    price: 680,
    images: ["https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=400&h=400&fit=crop"],
    category: "lentils",
    inStock: true,
    stockCount: 90,
    unit: "1kg",
  },
  {
    id: "p4",
    shopId: "1",
    name: "Nepali Masala Spice Mix",
    nameNepali: "नेपाली मसला",
    description: "Traditional blend of spices for authentic Nepali cooking. Perfect for curries and meat dishes.",
    price: 580,
    images: ["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop"],
    category: "spices",
    inStock: true,
    stockCount: 60,
    unit: "200g",
    featured: true,
  },
  {
    id: "p5",
    shopId: "1",
    name: "Frozen Momo Wrappers",
    nameNepali: "मम्म पिठो",
    description: "Ready-to-use momo wrappers. Make authentic Nepali momos at home. 40 pieces per pack.",
    price: 390,
    images: ["https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop"],
    category: "frozen",
    inStock: true,
    stockCount: 70,
    unit: "40 pcs",
  },

  // Everest Nepali Kitchen (id: 2) - food
  {
    id: "p6",
    shopId: "2",
    name: "Chicken Momo (Frozen, 20 pcs)",
    nameNepali: "कुखुराको मम्म (२० वटा)",
    description: "Handmade frozen chicken momos. Just steam and enjoy authentic Nepali dumplings at home.",
    price: 1200,
    compareAtPrice: 1400,
    images: ["https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=400&fit=crop"],
    category: "momo",
    inStock: true,
    stockCount: 50,
    unit: "20 pcs",
    featured: true,
  },
  {
    id: "p7",
    shopId: "2",
    name: "Sel Roti (Pack of 6)",
    nameNepali: "सेल रोटी",
    description: "Traditional ring-shaped sweet rice bread. A festival favorite, made fresh daily.",
    price: 700,
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop"],
    category: "sweets",
    inStock: true,
    stockCount: 40,
    unit: "6 pcs",
  },
  {
    id: "p8",
    shopId: "2",
    name: "Chicken Sukuti (Dried Meat) 200g",
    nameNepali: "कुखुराको सुकुटी",
    description: "Spicy Nepali dried chicken. A perfect snack with cold drinks. Packed fresh.",
    price: 1500,
    images: ["https://images.unsplash.com/photo-1606851091851-e8c8c0fca5ba?w=400&h=400&fit=crop"],
    category: "ready-to-eat",
    inStock: true,
    stockCount: 30,
    unit: "200g",
    featured: true,
  },

  // Nepal Fashion House (id: 3) - fashion
  {
    id: "p9",
    shopId: "3",
    name: "Daura Suruwal Set",
    nameNepali: "दौरा सुरुवाल सेट",
    description: "Traditional Nepali formal wear for men. Includes daura, suruwal, and topi. Perfect for Dashain and weddings.",
    price: 12800,
    compareAtPrice: 14500,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=400&fit=crop"],
    category: "traditional",
    inStock: true,
    stockCount: 15,
    variants: [
      { id: "v1", name: "Small", price: 12800, inStock: true },
      { id: "v2", name: "Medium", price: 12800, inStock: true },
      { id: "v3", name: "Large", price: 12800, inStock: true },
      { id: "v4", name: "XL", price: 13500, inStock: false },
    ],
    featured: true,
  },
  {
    id: "p10",
    shopId: "3",
    name: "Dhaka Topi",
    nameNepali: "ढाका टोपी",
    description: "Authentic Dhaka topi handwoven in Nepal. A symbol of Nepali pride to wear at festivals and events.",
    price: 2400,
    images: ["https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 40,
  },
  {
    id: "p11",
    shopId: "3",
    name: "Pashmina Shawl",
    nameNepali: "पश्मिना शल",
    description: "Luxurious 100% cashmere pashmina shawl, handwoven in Nepal. Warm and elegant for Japanese winters.",
    price: 9800,
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 25,
    featured: true,
  },

  // Kathmandu Handicrafts (id: 4) - handicrafts
  {
    id: "p12",
    shopId: "4",
    name: "Tibetan Singing Bowl",
    nameNepali: "तिब्बती गायन कटोरा",
    description: "Hand-hammered brass singing bowl for meditation and relaxation. Includes wooden mallet and cushion.",
    price: 8500,
    images: ["https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=400&h=400&fit=crop"],
    category: "singing-bowls",
    inStock: true,
    stockCount: 20,
    featured: true,
  },
  {
    id: "p13",
    shopId: "4",
    name: "Thangka Painting - Buddha",
    nameNepali: "थाङ्का चित्र - बुद्ध",
    description: "Hand-painted thangka of Buddha. Natural mineral colors on cotton canvas. A beautiful piece of home.",
    price: 38000,
    images: ["https://images.unsplash.com/photo-1609710228159-0fa9bd7c0827?w=400&h=400&fit=crop"],
    category: "thangka",
    inStock: true,
    stockCount: 8,
  },
  {
    id: "p14",
    shopId: "4",
    name: "Wooden Prayer Wheel",
    nameNepali: "काठको माने",
    description: "Traditional Buddhist prayer wheel with mantras. Handcrafted wood and brass.",
    price: 4800,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop"],
    category: "decor",
    inStock: true,
    stockCount: 15,
  },

  // Annapurna Grocery (id: 5) - groceries
  {
    id: "p15",
    shopId: "5",
    name: "Halal Goat Meat (Fresh) 1kg",
    nameNepali: "खसीको मासु १ केजी",
    description: "Fresh halal goat meat, cut to order. Perfect for khasi ko masu and festive feasts.",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=400&fit=crop"],
    category: "halal-meat",
    inStock: true,
    stockCount: 30,
    unit: "1kg",
    featured: true,
  },
  {
    id: "p16",
    shopId: "5",
    name: "Fresh Coriander & Green Chili Set",
    nameNepali: "धनिया र खुर्सानी",
    description: "Fresh coriander leaves and green chilies. Essential for authentic Nepali cooking.",
    price: 380,
    images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop"],
    category: "fresh-produce",
    inStock: true,
    stockCount: 45,
    unit: "set",
  },

  // Buddha Beauty & Wellness (id: 6) - health-beauty
  {
    id: "p17",
    shopId: "6",
    name: "Himalayan Herbal Face Serum",
    nameNepali: "हिमालयन फेस सीरम",
    description: "Natural anti-aging serum with Himalayan herbs. Brightens and hydrates skin in dry Japanese weather.",
    price: 2980,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop"],
    category: "skincare",
    inStock: true,
    stockCount: 30,
    featured: true,
  },
  {
    id: "p18",
    shopId: "6",
    name: "Natural Henna (Mehendi) Cones",
    nameNepali: "मेहन्दी",
    description: "Set of 4 natural henna cones for festivals and weddings. Rich, dark color.",
    price: 890,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop"],
    category: "henna",
    inStock: true,
    stockCount: 45,
  },

  // Sagarmatha Mart (id: 7) - groceries
  {
    id: "p19",
    shopId: "7",
    name: "Frozen Buff Momo (20 pcs)",
    nameNepali: "रांगाको मम्म",
    description: "Authentic frozen buff momos. Steam at home for a true taste of Kathmandu.",
    price: 1300,
    images: ["https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&h=400&fit=crop"],
    category: "frozen",
    inStock: true,
    stockCount: 40,
    unit: "20 pcs",
    featured: true,
  },
  {
    id: "p20",
    shopId: "7",
    name: "Tongba (Millet Drink) Kit",
    nameNepali: "तोङ्बा",
    description: "Traditional fermented millet drink kit with bamboo tongba container. A Himalayan favorite.",
    price: 3200,
    images: ["https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&h=400&fit=crop"],
    category: "beverages",
    inStock: true,
    stockCount: 12,
  },

  // Gorkha Spice Bazaar (id: 8) - food/spices
  {
    id: "p21",
    shopId: "8",
    name: "Timur (Sichuan Pepper) 100g",
    nameNepali: "टिमुर",
    description: "Aromatic Nepali timur pepper. The secret to authentic pickle and momo achar.",
    price: 980,
    compareAtPrice: 1200,
    images: ["https://images.unsplash.com/photo-1599909533730-f9ba0a3b7d6e?w=400&h=400&fit=crop"],
    category: "spices",
    inStock: true,
    stockCount: 50,
    unit: "100g",
    featured: true,
  },
  {
    id: "p22",
    shopId: "8",
    name: "Gundruk (Fermented Greens) 200g",
    nameNepali: "गुन्द्रुक",
    description: "Traditional fermented leafy greens. Make authentic gundruk ko jhol and achar.",
    price: 750,
    images: ["https://images.unsplash.com/photo-1591287083773-9a52cc8c7c0a?w=400&h=400&fit=crop"],
    category: "dry-foods",
    inStock: true,
    stockCount: 35,
    unit: "200g",
  },

  // Namaste Mart (id: 9) - groceries
  {
    id: "p23",
    shopId: "9",
    name: "Mustard Oil (Tori ko Tel) 1L",
    nameNepali: "तोरीको तेल",
    description: "Pure Nepali mustard oil. The authentic base for Nepali cooking and pickles.",
    price: 980,
    images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop"],
    category: "household",
    inStock: true,
    stockCount: 60,
    unit: "1L",
    featured: true,
  },
  {
    id: "p24",
    shopId: "9",
    name: "Beaten Rice (Chiura) 1kg",
    nameNepali: "चिउरा",
    description: "Traditional beaten rice. Perfect with curd, achar, and for festivals like Tihar.",
    price: 620,
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop"],
    category: "rice",
    inStock: true,
    stockCount: 50,
    unit: "1kg",
  },
  {
    id: "p25",
    shopId: "9",
    name: "Black Lentils (Kalo Dal) 1kg",
    nameNepali: "कालो दाल",
    description: "Whole black lentils for maas ko dal. A protein-rich Nepali staple.",
    price: 780,
    images: ["https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=400&h=400&fit=crop"],
    category: "lentils",
    inStock: true,
    stockCount: 55,
    unit: "1kg",
  },

  // Lumbini Jewelers (id: 10) - jewelry
  {
    id: "p26",
    shopId: "10",
    name: "Pote (Glass Bead Necklace)",
    nameNepali: "पोते",
    description: "Traditional green glass bead necklace, a symbol of marriage. Available in classic colors.",
    price: 3800,
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop"],
    category: "traditional",
    inStock: true,
    stockCount: 25,
    featured: true,
  },
  {
    id: "p27",
    shopId: "10",
    name: "Gold-Plated Tilhari",
    nameNepali: "तिलहरी",
    description: "Traditional Nepali tilhari pendant for pote. Essential bridal and festival jewelry.",
    price: 18500,
    images: ["https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400&h=400&fit=crop"],
    category: "gold",
    inStock: true,
    stockCount: 8,
  },

  // Pokhara Restaurant & Mart (id: 11) - food
  {
    id: "p28",
    shopId: "11",
    name: "Nepali Thali Set (Ready Meal)",
    nameNepali: "नेपाली थाली सेट",
    description: "Complete dal bhat thali with rice, dal, vegetable curry, and achar. Heat and eat.",
    price: 1100,
    compareAtPrice: 1300,
    images: ["https://images.unsplash.com/photo-1567337710282-00832b415979?w=400&h=400&fit=crop"],
    category: "thali",
    inStock: true,
    stockCount: 30,
    featured: true,
  },
  {
    id: "p29",
    shopId: "11",
    name: "Chicken Chowmein (Ready Meal)",
    nameNepali: "कुखुरा चाउमिन",
    description: "Nepali-style stir-fried noodles with chicken and vegetables. A diaspora favorite.",
    price: 850,
    images: ["https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&h=400&fit=crop"],
    category: "ready-to-eat",
    inStock: true,
    stockCount: 35,
  },
  {
    id: "p30",
    shopId: "11",
    name: "Veg Momo (Frozen, 20 pcs)",
    nameNepali: "तरकारी मम्म",
    description: "Vegetable momos made fresh and frozen. Steam at home for a quick comfort meal.",
    price: 1000,
    images: ["https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=400&fit=crop"],
    category: "momo",
    inStock: true,
    stockCount: 40,
  },

  // Manakamana Electronics (id: 12) - electronics
  {
    id: "p31",
    shopId: "12",
    name: "Japan Prepaid SIM Card",
    nameNepali: "जापान सिम कार्ड",
    description: "Data + calls prepaid SIM with Nepali-language support. Easy setup for newcomers to Japan.",
    price: 3000,
    images: ["https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=400&h=400&fit=crop"],
    category: "sim-cards",
    inStock: true,
    stockCount: 100,
    featured: true,
  },
  {
    id: "p32",
    shopId: "12",
    name: "Wireless Earbuds Pro",
    nameNepali: "वायरलेस इयरबड्स",
    description: "Active noise cancellation with 24-hour battery. Great for commutes on the Yamanote line.",
    price: 6800,
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 35,
  },
  {
    id: "p33",
    shopId: "12",
    name: "USB-C Fast Charger 65W",
    nameNepali: "फास्ट चार्जर",
    description: "Universal fast charger compatible with laptops and phones. Japanese plug type.",
    price: 3200,
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&h=400&fit=crop"],
    category: "accessories",
    inStock: true,
    stockCount: 50,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByShopId(shopId: string): Product[] {
  return products.filter((product) => product.shopId === shopId)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowerQuery) ||
      product.nameNepali?.includes(query) ||
      product.description.toLowerCase().includes(lowerQuery) ||
      product.category.toLowerCase().includes(lowerQuery)
  )
}

export function getProductsByCategory(shopId: string, category: string): Product[] {
  return products.filter(
    (product) => product.shopId === shopId && product.category === category
  )
}
