import type { Shop, OpeningHours } from "@/lib/types"

const defaultHours: OpeningHours = {
  monday: { open: "09:00", close: "20:00", isClosed: false },
  tuesday: { open: "09:00", close: "20:00", isClosed: false },
  wednesday: { open: "09:00", close: "20:00", isClosed: false },
  thursday: { open: "09:00", close: "20:00", isClosed: false },
  friday: { open: "09:00", close: "20:00", isClosed: false },
  saturday: { open: "10:00", close: "18:00", isClosed: false },
  sunday: { open: "10:00", close: "16:00", isClosed: false },
}

export const shops: Shop[] = [
  {
    id: "1",
    slug: "himalayan-grocery-store",
    name: "Himalayan Grocery Store",
    nameNepali: "हिमालयन किराना पसल",
    description: "Your one-stop shop for fresh vegetables, fruits, and daily essentials. We source directly from local farmers to bring you the freshest produce in Kathmandu.",
    category: "groceries",
    subcategories: ["fresh-produce", "dairy", "spices", "snacks"],
    coverImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 234,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "Thamel Marg, Near Garden of Dreams",
      ward: "26",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.7154, lng: 85.3123 },
    },
    contact: { phone: "+977-1-4701234", whatsapp: "+977-9841234567" },
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 500,
    deliveryFee: 50,
    deliveryTime: "30-45 min",
    featured: true,
  },
  {
    id: "2",
    slug: "nepal-fashion-house",
    name: "Nepal Fashion House",
    nameNepali: "नेपाल फेसन हाउस",
    description: "Traditional and modern Nepali clothing for all occasions. From daura suruwal to contemporary western wear, we have something for everyone.",
    category: "fashion",
    subcategories: ["traditional", "western", "accessories", "footwear"],
    coverImage: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=200&h=200&fit=crop",
    rating: 4.6,
    reviewCount: 189,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "New Road, Opposite to Bishal Bazaar",
      ward: "22",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.7050, lng: 85.3130 },
    },
    contact: { phone: "+977-1-4234567", whatsapp: "+977-9801234567" },
    features: ["pickup", "cash-on-delivery", "digital-payment"],
    featured: true,
  },
  {
    id: "3",
    slug: "tech-hub-electronics",
    name: "Tech Hub Electronics",
    nameNepali: "टेक हब इलेक्ट्रोनिक्स",
    description: "Latest smartphones, laptops, and gadgets at competitive prices. Authorized dealer for major brands with genuine warranty.",
    category: "electronics",
    subcategories: ["smartphones", "laptops", "accessories", "gaming"],
    coverImage: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&h=200&fit=crop",
    rating: 4.5,
    reviewCount: 312,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "New Baneshwor, Kathmandu Plaza",
      ward: "10",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.6915, lng: 85.3420 },
    },
    contact: { phone: "+977-1-4567890", whatsapp: "+977-9851234567" },
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1000,
    deliveryFee: 100,
    deliveryTime: "1-2 days",
    featured: true,
  },
  {
    id: "4",
    slug: "patan-handicrafts",
    name: "Patan Handicrafts",
    nameNepali: "पाटन हस्तकला",
    description: "Authentic Nepali handicrafts made by local artisans. From singing bowls to thangka paintings, discover the rich cultural heritage of Nepal.",
    category: "handicrafts",
    subcategories: ["singing-bowls", "thangka", "wood-carving", "metal-work"],
    coverImage: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 156,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      sunday: { open: "00:00", close: "00:00", isClosed: true },
    },
    location: {
      address: "Patan Durbar Square, Mangal Bazaar",
      ward: "12",
      municipality: "Lalitpur Metropolitan City",
      district: "Lalitpur",
      coordinates: { lat: 27.6727, lng: 85.3250 },
    },
    contact: { phone: "+977-1-5521234", whatsapp: "+977-9861234567" },
    features: ["pickup", "delivery", "digital-payment"],
    deliveryFee: 150,
    deliveryTime: "2-3 days",
    featured: true,
  },
  {
    id: "5",
    slug: "glow-beauty-store",
    name: "Glow Beauty Store",
    nameNepali: "ग्लो ब्युटी स्टोर",
    description: "Premium skincare, makeup, and beauty products. We carry both international brands and natural Nepali beauty products.",
    category: "health-beauty",
    subcategories: ["skincare", "makeup", "haircare", "wellness"],
    coverImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 278,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "Jawalakhel, Opposite Zoo",
      ward: "7",
      municipality: "Lalitpur Metropolitan City",
      district: "Lalitpur",
      coordinates: { lat: 27.6710, lng: 85.3150 },
    },
    contact: { phone: "+977-1-5534567", whatsapp: "+977-9871234567" },
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 300,
    deliveryFee: 60,
    deliveryTime: "45-60 min",
  },
  {
    id: "6",
    slug: "book-worm-corner",
    name: "Book Worm Corner",
    nameNepali: "बुक वर्म कर्नर",
    description: "A paradise for book lovers. From bestsellers to rare Nepali literature, find your next great read here.",
    category: "books-stationery",
    subcategories: ["fiction", "non-fiction", "nepali-literature", "stationery"],
    coverImage: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 167,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "Pulchowk, Engineering Campus Road",
      ward: "6",
      municipality: "Lalitpur Metropolitan City",
      district: "Lalitpur",
      coordinates: { lat: 27.6785, lng: 85.3180 },
    },
    contact: { phone: "+977-1-5512345" },
    features: ["pickup", "cash-on-delivery"],
  },
  {
    id: "7",
    slug: "bhaktapur-pottery",
    name: "Bhaktapur Pottery House",
    nameNepali: "भक्तपुर माटोका भाँडा पसल",
    description: "Traditional pottery and ceramics from Bhaktapur. Each piece is handcrafted by skilled artisans using centuries-old techniques.",
    category: "home-decor",
    subcategories: ["pottery", "ceramics", "planters", "decorative"],
    coverImage: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 98,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      saturday: { open: "09:00", close: "17:00", isClosed: false },
    },
    location: {
      address: "Potter's Square, Bhaktapur",
      ward: "8",
      municipality: "Bhaktapur Municipality",
      district: "Bhaktapur",
      coordinates: { lat: 27.6722, lng: 85.4283 },
    },
    contact: { phone: "+977-1-6612345", whatsapp: "+977-9881234567" },
    features: ["pickup", "delivery", "cash-on-delivery"],
    deliveryFee: 200,
    deliveryTime: "3-5 days",
  },
  {
    id: "8",
    slug: "everest-sports",
    name: "Everest Sports & Outdoor",
    nameNepali: "एभरेस्ट स्पोर्ट्स",
    description: "Everything you need for trekking, climbing, and outdoor adventures. Quality gear from trusted brands.",
    category: "sports-fitness",
    subcategories: ["trekking", "climbing", "camping", "fitness"],
    coverImage: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1461896836934- voices?w=200&h=200&fit=crop",
    rating: 4.6,
    reviewCount: 203,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "Thamel, JP Road",
      ward: "26",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.7160, lng: 85.3100 },
    },
    contact: { phone: "+977-1-4701111", whatsapp: "+977-9891234567" },
    features: ["delivery", "pickup", "digital-payment"],
    minOrder: 2000,
    deliveryFee: 100,
    deliveryTime: "1-2 days",
  },
  {
    id: "9",
    slug: "newari-sweets",
    name: "Newari Sweets & Snacks",
    nameNepali: "नेवारी मिठाई तथा खाजा",
    description: "Authentic Newari delicacies and traditional sweets. From yomari to chatamari, taste the flavors of Newar cuisine.",
    category: "food-beverages",
    subcategories: ["sweets", "snacks", "traditional", "beverages"],
    coverImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 445,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      monday: { open: "07:00", close: "21:00", isClosed: false },
      tuesday: { open: "07:00", close: "21:00", isClosed: false },
      wednesday: { open: "07:00", close: "21:00", isClosed: false },
      thursday: { open: "07:00", close: "21:00", isClosed: false },
      friday: { open: "07:00", close: "21:00", isClosed: false },
      saturday: { open: "07:00", close: "22:00", isClosed: false },
      sunday: { open: "08:00", close: "20:00", isClosed: false },
    },
    location: {
      address: "Ason, Indrachowk",
      ward: "24",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.7055, lng: 85.3100 },
    },
    contact: { phone: "+977-1-4222333", whatsapp: "+977-9801111222" },
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 200,
    deliveryFee: 40,
    deliveryTime: "20-30 min",
    featured: true,
  },
  {
    id: "10",
    slug: "gold-silver-jewelers",
    name: "Lakshmi Gold & Silver",
    nameNepali: "लक्ष्मी सुनचाँदी पसल",
    description: "Fine gold and silver jewelry with traditional Nepali designs. Custom orders and repairs available.",
    category: "jewelry",
    subcategories: ["gold", "silver", "traditional", "custom"],
    coverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 89,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      sunday: { open: "00:00", close: "00:00", isClosed: true },
    },
    location: {
      address: "Mangal Bazaar, Patan",
      ward: "12",
      municipality: "Lalitpur Metropolitan City",
      district: "Lalitpur",
      coordinates: { lat: 27.6730, lng: 85.3255 },
    },
    contact: { phone: "+977-1-5523456" },
    features: ["pickup", "digital-payment"],
  },
  {
    id: "11",
    slug: "organic-farm-fresh",
    name: "Organic Farm Fresh",
    nameNepali: "अर्गानिक फार्म फ्रेश",
    description: "100% organic vegetables and fruits delivered fresh from our partner farms in the valley. Supporting local farmers.",
    category: "groceries",
    subcategories: ["organic", "fresh-produce", "dairy", "eggs"],
    coverImage: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 178,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      monday: { open: "06:00", close: "19:00", isClosed: false },
      tuesday: { open: "06:00", close: "19:00", isClosed: false },
      wednesday: { open: "06:00", close: "19:00", isClosed: false },
      thursday: { open: "06:00", close: "19:00", isClosed: false },
      friday: { open: "06:00", close: "19:00", isClosed: false },
      saturday: { open: "06:00", close: "18:00", isClosed: false },
      sunday: { open: "07:00", close: "14:00", isClosed: false },
    },
    location: {
      address: "Bouddha, Tinchuli",
      ward: "6",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.7215, lng: 85.3620 },
    },
    contact: { phone: "+977-1-4489012", whatsapp: "+977-9812345678" },
    features: ["delivery", "cash-on-delivery", "digital-payment"],
    minOrder: 800,
    deliveryFee: 60,
    deliveryTime: "Same day (order by 2pm)",
  },
  {
    id: "12",
    slug: "trendy-threads",
    name: "Trendy Threads Boutique",
    nameNepali: "ट्रेन्डी थ्रेड्स बुटिक",
    description: "Contemporary fashion for the modern Nepali. Curated collection of trendy clothing and accessories.",
    category: "fashion",
    subcategories: ["women", "men", "accessories", "shoes"],
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=200&h=200&fit=crop",
    rating: 4.5,
    reviewCount: 234,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "Durbar Marg, Opposite Hotel Annapurna",
      ward: "11",
      municipality: "Kathmandu Metropolitan City",
      district: "Kathmandu",
      coordinates: { lat: 27.7130, lng: 85.3200 },
    },
    contact: { phone: "+977-1-4225566", whatsapp: "+977-9823456789" },
    features: ["delivery", "pickup", "digital-payment"],
    deliveryFee: 100,
    deliveryTime: "1-2 days",
  },
]

export function getShopBySlug(slug: string): Shop | undefined {
  return shops.find((shop) => shop.slug === slug)
}

export function getShopById(id: string): Shop | undefined {
  return shops.find((shop) => shop.id === id)
}

export function getShopsByCategory(category: string): Shop[] {
  return shops.filter((shop) => shop.category === category)
}

export function getFeaturedShops(): Shop[] {
  return shops.filter((shop) => shop.featured)
}

export function searchShops(query: string): Shop[] {
  const lowerQuery = query.toLowerCase()
  return shops.filter(
    (shop) =>
      shop.name.toLowerCase().includes(lowerQuery) ||
      shop.nameNepali?.includes(query) ||
      shop.description.toLowerCase().includes(lowerQuery) ||
      shop.category.includes(lowerQuery)
  )
}
