import type { Shop, OpeningHours } from "@/lib/types"

const defaultHours: OpeningHours = {
  monday: { open: "10:00", close: "21:00", isClosed: false },
  tuesday: { open: "10:00", close: "21:00", isClosed: false },
  wednesday: { open: "10:00", close: "21:00", isClosed: false },
  thursday: { open: "10:00", close: "21:00", isClosed: false },
  friday: { open: "10:00", close: "22:00", isClosed: false },
  saturday: { open: "10:00", close: "22:00", isClosed: false },
  sunday: { open: "10:00", close: "21:00", isClosed: false },
}

export const shops: Shop[] = [
  {
    id: "1",
    slug: "himalaya-asian-mart",
    name: "Himalaya Asian Mart",
    nameNepali: "हिमालय एसियन मार्ट",
    description: "Shin-Okubo's favorite Nepali grocery store. Find authentic Nepali spices, lentils, rice, momo wrappers, and hard-to-get ingredients straight from home. We ship across Japan.",
    category: "groceries",
    subcategories: ["spices", "lentils", "rice", "snacks"],
    coverImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 412,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "1-12-5 Hyakunincho",
      area: "Shin-Okubo",
      city: "Shinjuku",
      prefecture: "Tokyo",
      postalCode: "169-0073",
      coordinates: { lat: 35.7012, lng: 139.7003 },
    },
    contact: { phone: "+81-3-1234-5678", whatsapp: "+81-90-1234-5678" },
    googleMapsTag: "ネパール物産店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7012,139.7003",
    onlineStoreUrl: "/shops/himalaya-asian-mart",
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1500,
    deliveryFee: 500,
    deliveryTime: "1-2 days",
    featured: true,
  },
  {
    id: "2",
    slug: "everest-nepali-kitchen",
    name: "Everest Nepali Kitchen",
    nameNepali: "एभरेस्ट नेपाली किचन",
    description: "Home-cooked Nepali momo, sel roti, sukuti, and achar made fresh daily. Order our frozen momo packs and festival specials for delivery anywhere in Japan.",
    category: "food-beverages",
    subcategories: ["momo", "sweets", "achar", "ready-to-eat"],
    coverImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 587,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      monday: { open: "11:00", close: "22:00", isClosed: false },
      tuesday: { open: "11:00", close: "22:00", isClosed: false },
      wednesday: { open: "11:00", close: "22:00", isClosed: false },
      thursday: { open: "11:00", close: "22:00", isClosed: false },
      friday: { open: "11:00", close: "23:00", isClosed: false },
      saturday: { open: "11:00", close: "23:00", isClosed: false },
      sunday: { open: "11:00", close: "22:00", isClosed: false },
    },
    location: {
      address: "2-1-3 Okubo",
      area: "Okubo",
      city: "Shinjuku",
      prefecture: "Tokyo",
      postalCode: "169-0072",
      coordinates: { lat: 35.7008, lng: 139.6970 },
    },
    contact: { phone: "+81-3-2345-6789", whatsapp: "+81-90-2345-6789" },
    googleMapsTag: "ネパール料理店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7008,139.6970",
    onlineStoreUrl: "/shops/everest-nepali-kitchen",
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1000,
    deliveryFee: 400,
    deliveryTime: "Same day (order by 3pm)",
    featured: true,
  },
  {
    id: "3",
    slug: "nepal-fashion-house",
    name: "Nepal Fashion House",
    nameNepali: "नेपाल फेसन हाउस",
    description: "Traditional Nepali clothing for the diaspora. Daura suruwal, sarees, kurta, dhaka topi, and festival wear for Dashain, Tihar, and weddings. Delivered across Japan.",
    category: "fashion",
    subcategories: ["traditional", "festival-wear", "accessories", "saree"],
    coverImage: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=200&h=200&fit=crop",
    rating: 4.6,
    reviewCount: 213,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "1-2-9 Takadanobaba",
      area: "Takadanobaba",
      city: "Shinjuku",
      prefecture: "Tokyo",
      postalCode: "169-0075",
      coordinates: { lat: 35.7126, lng: 139.7038 },
    },
    contact: { phone: "+81-3-3456-7890", whatsapp: "+81-90-3456-7890" },
    googleMapsTag: "民族衣装店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7126,139.7038",
    onlineStoreUrl: "/shops/nepal-fashion-house",
    features: ["pickup", "delivery", "digital-payment"],
    minOrder: 2000,
    deliveryFee: 600,
    deliveryTime: "2-3 days",
    featured: true,
  },
  {
    id: "4",
    slug: "kathmandu-handicrafts",
    name: "Kathmandu Handicrafts",
    nameNepali: "काठमाडौं हस्तकला",
    description: "Authentic Nepali handicrafts imported to Japan. Singing bowls, thangka paintings, pashmina, and handmade decor that brings a piece of home to your apartment.",
    category: "handicrafts",
    subcategories: ["singing-bowls", "thangka", "pashmina", "decor"],
    coverImage: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 168,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      tuesday: { open: "00:00", close: "00:00", isClosed: true },
    },
    location: {
      address: "3-15-2 Ueno",
      area: "Ueno",
      city: "Taito",
      prefecture: "Tokyo",
      postalCode: "110-0005",
      coordinates: { lat: 35.7141, lng: 139.7774 },
    },
    contact: { phone: "+81-3-4567-8901", whatsapp: "+81-90-4567-8901" },
    googleMapsTag: "民芸品店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7141,139.7774",
    onlineStoreUrl: "/shops/kathmandu-handicrafts",
    features: ["pickup", "delivery", "digital-payment"],
    deliveryFee: 700,
    deliveryTime: "2-4 days",
    featured: true,
  },
  {
    id: "5",
    slug: "annapurna-grocery-kawaguchi",
    name: "Annapurna Grocery",
    nameNepali: "अन्नपूर्ण किराना",
    description: "Serving the Nepali community of Saitama. Fresh vegetables, halal meat, Nepali spices, and daily essentials. Convenient delivery to Kawaguchi and Warabi.",
    category: "groceries",
    subcategories: ["fresh-produce", "halal-meat", "spices", "dairy"],
    coverImage: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 256,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "2-4-1 Namiki",
      area: "Nishi-Kawaguchi",
      city: "Kawaguchi",
      prefecture: "Saitama",
      postalCode: "332-0021",
      coordinates: { lat: 35.8074, lng: 139.6932 },
    },
    contact: { phone: "+81-48-123-4567", whatsapp: "+81-90-5678-9012" },
    googleMapsTag: "アジア物産",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.8074,139.6932",
    onlineStoreUrl: "/shops/annapurna-grocery-kawaguchi",
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1500,
    deliveryFee: 450,
    deliveryTime: "Same day (order by 2pm)",
    featured: true,
  },
  {
    id: "6",
    slug: "buddha-beauty-store",
    name: "Buddha Beauty & Wellness",
    nameNepali: "बुद्ध ब्युटी स्टोर",
    description: "Natural Himalayan skincare, ayurvedic products, henna, and beauty essentials popular among the Nepali community in Japan.",
    category: "health-beauty",
    subcategories: ["skincare", "ayurveda", "henna", "haircare"],
    coverImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 189,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "1-8-4 Nishi-Nippori",
      area: "Nippori",
      city: "Arakawa",
      prefecture: "Tokyo",
      postalCode: "116-0013",
      coordinates: { lat: 35.7281, lng: 139.7707 },
    },
    contact: { phone: "+81-3-5678-9012", whatsapp: "+81-90-6789-0123" },
    googleMapsTag: "化粧品店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7281,139.7707",
    onlineStoreUrl: "/shops/buddha-beauty-store",
    features: ["delivery", "pickup", "digital-payment"],
    minOrder: 1000,
    deliveryFee: 400,
    deliveryTime: "1-2 days",
  },
  {
    id: "7",
    slug: "sagarmatha-mart-yokohama",
    name: "Sagarmatha Mart",
    nameNepali: "सगरमाथा मार्ट",
    description: "Kanagawa's go-to Nepali and South Asian grocery. Imported snacks, beverages, spices, and frozen Nepali foods. Delivery across Yokohama and Kawasaki.",
    category: "groceries",
    subcategories: ["spices", "snacks", "frozen", "beverages"],
    coverImage: "https://images.unsplash.com/photo-1601599963565-b7f49d6c2f1a?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1601599561213-832382fd07ba?w=200&h=200&fit=crop",
    rating: 4.6,
    reviewCount: 203,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "2-16-1 Minamisaiwai",
      area: "Yokohama Station",
      city: "Yokohama",
      prefecture: "Kanagawa",
      postalCode: "220-0011",
      coordinates: { lat: 35.4659, lng: 139.6224 },
    },
    contact: { phone: "+81-45-123-4567", whatsapp: "+81-90-7890-1234" },
    googleMapsTag: "アジア物産",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.4659,139.6224",
    onlineStoreUrl: "/shops/sagarmatha-mart-yokohama",
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1500,
    deliveryFee: 500,
    deliveryTime: "1-2 days",
  },
  {
    id: "8",
    slug: "gorkha-spice-bazaar",
    name: "Gorkha Spice Bazaar",
    nameNepali: "गोर्खा मसला बजार",
    description: "Specialty Nepali spices, pickles, and dry foods. From timur to gundruk, we stock the authentic flavors you can't find in regular Japanese supermarkets.",
    category: "food-beverages",
    subcategories: ["spices", "achar", "dry-foods", "tea"],
    coverImage: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 145,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "1-5-7 Tsuruhashi",
      area: "Tsuruhashi",
      city: "Ikuno",
      prefecture: "Osaka",
      postalCode: "544-0031",
      coordinates: { lat: 34.6648, lng: 135.5310 },
    },
    contact: { phone: "+81-6-1234-5678", whatsapp: "+81-90-8901-2345" },
    googleMapsTag: "ネパール物産店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=34.6648,135.5310",
    onlineStoreUrl: "/shops/gorkha-spice-bazaar",
    features: ["delivery", "pickup", "digital-payment"],
    minOrder: 1200,
    deliveryFee: 500,
    deliveryTime: "2-3 days",
  },
  {
    id: "9",
    slug: "namaste-mart-nagoya",
    name: "Namaste Mart",
    nameNepali: "नमस्ते मार्ट",
    description: "Aichi's largest Nepali grocery serving the Nagoya community. Rice, lentils, spices, fresh vegetables, and Nepali household items at great prices.",
    category: "groceries",
    subcategories: ["rice", "lentils", "spices", "household"],
    coverImage: "https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 178,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "3-6-1 Sakae",
      area: "Sakae, Nagoya",
      city: "Nagoya",
      prefecture: "Aichi",
      postalCode: "460-0008",
      coordinates: { lat: 35.1681, lng: 136.9085 },
    },
    contact: { phone: "+81-52-123-4567", whatsapp: "+81-90-9012-3456" },
    googleMapsTag: "アジア食材店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.1681,136.9085",
    onlineStoreUrl: "/shops/namaste-mart-nagoya",
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1500,
    deliveryFee: 500,
    deliveryTime: "1-2 days",
    featured: true,
  },
  {
    id: "10",
    slug: "lumbini-jewelers",
    name: "Lumbini Jewelers",
    nameNepali: "लुम्बिनी ज्वेलर्स",
    description: "Traditional Nepali gold and silver jewelry for weddings and festivals. Tilhari, pote, and custom designs for the Nepali community in Japan.",
    category: "jewelry",
    subcategories: ["gold", "silver", "traditional", "custom"],
    coverImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 92,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      tuesday: { open: "00:00", close: "00:00", isClosed: true },
    },
    location: {
      address: "2-7-3 Hyakunincho",
      area: "Shin-Okubo",
      city: "Shinjuku",
      prefecture: "Tokyo",
      postalCode: "169-0073",
      coordinates: { lat: 35.7018, lng: 139.6995 },
    },
    contact: { phone: "+81-3-6789-0123", whatsapp: "+81-90-0123-4567" },
    googleMapsTag: "宝石店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7018,139.6995",
    onlineStoreUrl: "/shops/lumbini-jewelers",
    features: ["pickup", "digital-payment"],
  },
  {
    id: "11",
    slug: "pokhara-restaurant-mart",
    name: "Pokhara Restaurant & Mart",
    nameNepali: "पोखरा रेस्टुरेन्ट तथा मार्ट",
    description: "Authentic Nepali thali, momo, and chowmein plus a grocery corner. Order ready meals or stock up on Nepali pantry staples in Warabi.",
    category: "food-beverages",
    subcategories: ["ready-to-eat", "momo", "thali", "groceries"],
    coverImage: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 334,
    isOpen: true,
    openingHours: {
      ...defaultHours,
      monday: { open: "11:00", close: "22:30", isClosed: false },
      tuesday: { open: "11:00", close: "22:30", isClosed: false },
      wednesday: { open: "11:00", close: "22:30", isClosed: false },
      thursday: { open: "11:00", close: "22:30", isClosed: false },
      friday: { open: "11:00", close: "23:00", isClosed: false },
      saturday: { open: "11:00", close: "23:00", isClosed: false },
      sunday: { open: "11:00", close: "22:30", isClosed: false },
    },
    location: {
      address: "1-3-8 Chuo",
      area: "Warabi Station",
      city: "Warabi",
      prefecture: "Saitama",
      postalCode: "335-0004",
      coordinates: { lat: 35.8254, lng: 139.6800 },
    },
    contact: { phone: "+81-48-234-5678", whatsapp: "+81-90-1122-3344" },
    googleMapsTag: "ネパール料理店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.8254,139.6800",
    onlineStoreUrl: "/shops/pokhara-restaurant-mart",
    features: ["delivery", "pickup", "cash-on-delivery", "digital-payment"],
    minOrder: 1000,
    deliveryFee: 400,
    deliveryTime: "Same day (order by 4pm)",
  },
  {
    id: "12",
    slug: "manakamana-electronics",
    name: "Manakamana Electronics",
    nameNepali: "मनकामना इलेक्ट्रोनिक्स",
    description: "Phones, SIM cards, remittance support, and electronics tailored for the Nepali community in Japan. Nepali-speaking staff to help you get connected.",
    category: "electronics",
    subcategories: ["smartphones", "sim-cards", "accessories", "appliances"],
    coverImage: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=400&fit=crop",
    logo: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&h=200&fit=crop",
    rating: 4.5,
    reviewCount: 167,
    isOpen: true,
    openingHours: defaultHours,
    location: {
      address: "1-10-2 Hyakunincho",
      area: "Shin-Okubo",
      city: "Shinjuku",
      prefecture: "Tokyo",
      postalCode: "169-0073",
      coordinates: { lat: 35.7005, lng: 139.7010 },
    },
    contact: { phone: "+81-3-7890-1234", whatsapp: "+81-90-2233-4455" },
    googleMapsTag: "電器店",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=35.7005,139.7010",
    onlineStoreUrl: "/shops/manakamana-electronics",
    features: ["delivery", "pickup", "digital-payment"],
    minOrder: 2000,
    deliveryFee: 600,
    deliveryTime: "2-3 days",
  },
]

export function getShopBySlug(slug: string): Shop | undefined {
  return shops.find((shop) => shop.slug === slug)
}

export function getShopById(id: string): Shop | undefined {
  return shops.find((shop) => shop.id === id)
}

export function getShopsByCategory(category: string): Shop[] {
  return shops.filter((shop) => shop.category === category)
}

export function getFeaturedShops(): Shop[] {
  return shops.filter((shop) => shop.featured)
}

export function searchShops(query: string): Shop[] {
  const lowerQuery = query.toLowerCase()
  return shops.filter(
    (shop) =>
      shop.name.toLowerCase().includes(lowerQuery) ||
      shop.nameNepali?.includes(query) ||
      shop.description.toLowerCase().includes(lowerQuery) ||
      shop.category.includes(lowerQuery)
  )
}
