import type { CustomerProfile } from "@/lib/types"

// The currently "logged-in" customer for this mock session.
// In a real system this would come from the authenticated session.
export const currentCustomer: CustomerProfile = {
  id: "cust-001",
  name: "Prabin Shrestha",
  nameNepali: "प्रबिन श्रेष्ठ",
  email: "prabin.shrestha@example.com",
  phone: "+81-90-1234-5678",
  avatar: "",
  joinedAt: "2025-03-18",
  preferredLanguage: "en",
  addresses: [
    {
      id: "addr-1",
      label: "Home",
      fullName: "Prabin Shrestha",
      phone: "+81-90-1234-5678",
      postalCode: "169-0073",
      prefecture: "Tokyo",
      city: "Shinjuku",
      address: "Hyakunincho 2-1-1",
      building: "Sakura Heights 301",
      isDefault: true,
    },
    {
      id: "addr-2",
      label: "Work",
      fullName: "Prabin Shrestha",
      phone: "+81-90-1234-5678",
      postalCode: "160-0023",
      prefecture: "Tokyo",
      city: "Shinjuku",
      address: "Nishi-Shinjuku 6-5-1",
      building: "Tower Office 12F",
      isDefault: false,
    },
  ],
  recentOrders: [
    {
      id: "ORD-10428",
      shopName: "Himalaya Asian Mart",
      shopSlug: "himalaya-asian-mart",
      date: "2026-06-12",
      itemCount: 4,
      total: 4830,
      status: "out-for-delivery",
    },
    {
      id: "ORD-10390",
      shopName: "Everest Nepali Kitchen",
      shopSlug: "everest-nepali-kitchen",
      date: "2026-06-05",
      itemCount: 2,
      total: 2640,
      status: "delivered",
    },
    {
      id: "ORD-10355",
      shopName: "Himalaya Asian Mart",
      shopSlug: "himalaya-asian-mart",
      date: "2026-05-28",
      itemCount: 6,
      total: 7180,
      status: "delivered",
    },
    {
      id: "ORD-10311",
      shopName: "Annapurna Grocery",
      shopSlug: "annapurna-grocery-kawaguchi",
      date: "2026-05-14",
      itemCount: 3,
      total: 3520,
      status: "delivered",
    },
  ],
  favoriteShopSlugs: ["himalaya-asian-mart", "everest-nepali-kitchen", "gorkha-spice-bazaar"],
  notifications: {
    orderUpdates: true,
    promotions: true,
    newShops: false,
    newsletter: true,
  },
}
